// libraries/svelte/src/components/ComponentWithDifferentViews.svelte
<div id="ce-with-different-views">
    <button on:click={toggle}>Toggle views</button>
    {#if showWC}
        <ce-with-children></ce-with-children>
    {:else}
        <div>Dummy view</div>
    {/if}
</div>

<script>
  let showWC = true;

  export function toggle() {
    showWC = !showWC;
  }
</script>

// libraries/vue/src/components/ComponentWithDifferentViews.vue
<script setup>
import {ref} from 'vue';

import 'wc/ce-with-children';

const showWC = ref(true);

</script>

<template>
  <div id="ce-with-different-views">
    <button @click="() => showWC = !showWC">Toggle views</button>
    <ce-with-children v-if="showWC"></ce-with-children>
    <div v-else>Dummy view</div>
  </div>
</template>
