// libraries/stencil/src/components/component-with-imperative-event.tsx
import { Component, Host, h, Prop } from "@stencil/core";

import "wc/ce-with-event";

@Component({
  tag: "component-with-imperative-event",
  shadow: true
})
export class ComponentWithImperativeEvent {
  @Prop({ mutable: true }) eventHandled = false;

  customEl!: HTMLElement;

  componentDidLoad() {
    this.customEl.addEventListener(
      "camelEvent",
      () => (this.eventHandled = true)
    );
  }

  render() {
    return (
      <Host>
        <div id="ce-with-imperative-event-handled">{this.eventHandled.toString()}</div>
        <ce-with-event id="ce-with-imperative-event" ref={el => (this.customEl = el)}>Imperative</ce-with-event>
      </Host>
    );
  }
}

// libraries/vue/src/components/ComponentWithImperativeEvent.vue
<script setup>
import {ref, useTemplateRef, onMounted} from 'vue';

import 'wc/ce-with-event';

const eventHandled = ref(false);
const ce = useTemplateRef('ce');

onMounted(() => {
  ce.value.addEventListener('camelEvent', () => eventHandled.value = true)
})

</script>

<template>
  <div id="ce-with-imperative-event-handled">{{ eventHandled.toString() }}</div>
  <ce-with-event id="ce-with-imperative-event" ref="ce">
    Imperative
  </ce-with-event>
</template>
