// libraries/vue/src/components/ComponentWithImperativeEvent.vue
<script setup>
import {ref, useTemplateRef, onMounted} from 'vue';

import 'wc/ce-with-event';

const eventHandled = ref(false);
const ce = useTemplateRef('ce');

onMounted(() => {
  ce.value.addEventListener('camelEvent', () => eventHandled.value = true)
})

</script>

<template>
  <div id="ce-with-imperative-event-handled">{{ eventHandled.toString() }}</div>
  <ce-with-event id="ce-with-imperative-event" ref="ce">
    Imperative
  </ce-with-event>
</template>

// libraries/stencil/src/components/component-with-imperative-event/component-with-imperative-event.tsx
import { Component, Host, h, Prop } from '@stencil/core';

@Component({
  tag: 'component-with-imperative-event',
  shadow: true
})
export class ComponentWithImperativeEvent {

  @Prop() eventHandled = false;

  customEl!: HTMLElement;

  componentDidLoad() {
    this.customEl.addEventListener('camelEvent', () => this.eventHandled = true);
  }

  render() {
    return (
      <Host>
        <div id="handled">{this.eventHandled.toString()}</div>
        <ce-with-event id="wc" ref={(el) => this.customEl = el}></ce-with-event>
      </Host>
    );
  }
}
