// libraries/solid/src/index.jsx
import {render} from 'solid-js/web';
import {
  ComponentWithChildren,
  ComponentWithChildrenRerender, ComponentWithDeclarativeEvent,
  ComponentWithDifferentViews, ComponentWithImperativeEvent,
  ComponentWithoutChildren, ComponentWithProperties
} from "./components";

const App = () => {
  return <>
    <ComponentWithoutChildren />
    <ComponentWithChildren/>
    <ComponentWithChildrenRerender />
    <ComponentWithDifferentViews />
    <ComponentWithProperties />
    <ComponentWithDeclarativeEvent />
    <ComponentWithImperativeEvent />
  </>
}

render(() => <App />, document.getElementById('harness'));

// libraries/react/src/index.jsx
import React from "react";
import { createRoot } from "react-dom/client";
import * as Component from './components';

const Harness = () => {
  return <>
    <Component.ComponentWithoutChildren />
    <Component.ComponentWithChildren />
    <Component.ComponentWithChildrenRerender />
    <Component.ComponentWithDifferentViews />
    <Component.ComponentWithProperties />
    <Component.ComponentWithDeclarativeEvent />
    <Component.ComponentWithImperativeEvent />
  </>
}

createRoot(document.getElementById("harness")).render(<Harness />);
