// libraries/svelte/src/components/ComponentWithDeclarativeEvent.svelte
<div id="lowercase">{lowercaseHandled}</div>
<div id="kebab">{kebabHandled}</div>
<div id="camel">{camelHandled}</div>
<div id="caps">{capsHandled}</div>
<div id="pascal">{pascalHandled}</div>
<ce-with-event id="wc"
    on:lowercaseevent={() => lowercaseHandled = true}
    on:kebab-event={() => kebabHandled = true}
    on:camelEvent={() => camelHandled = true}
    on:CAPSevent={() => capsHandled = true}
    on:PascalEvent={() => pascalHandled = true}>
</ce-with-event> 

<script>
    let lowercaseHandled = false;
    let kebabHandled = false;
    let camelHandled = false;
    let capsHandled = false;
    let pascalHandled = false;
</script>

// libraries/stencil/src/components/component-with-declarative-event/component-with-declarative-event.tsx
import { Component, Host, h, Prop } from "@stencil/core";

@Component({
  tag: "component-with-declarative-event",
  shadow: true
})
export class ComponentWithDeclarativeEvent {
  @Prop() lowercaseHandled = false;
  @Prop() kebabHandled = false;
  @Prop() camelHandled = false;
  @Prop() capsHandled = false;
  @Prop() pascalHandled = false;

  render() {
    return (
      <Host>
        <div id="lowercase">{this.lowercaseHandled.toString()}</div>
        <div id="kebab">{this.kebabHandled.toString()}</div>
        <div id="camel">{this.camelHandled.toString()}</div>
        <div id="caps">{this.capsHandled.toString()}</div>
        <div id="pascal">{this.pascalHandled.toString()}</div>
        <ce-with-event
          id="wc"
          on-lowercaseevent={_ => (this.lowercaseHandled = true)}
          on-kebab-event={_ => (this.kebabHandled = true)}
          on-camelEvent={_ => (this.camelHandled = true)}
          on-CAPSevent={_ => (this.capsHandled = true)}
          on-PascalEvent={_ => (this.pascalHandled = true)}
        ></ce-with-event>
      </Host>
    );
  }
}
