// counter/vue/src/App.vue
<template>
  <div id="app">
    <x-count>{{count}}</x-count>
    <x-count-with-shadow>{{count}}</x-count-with-shadow>
  </div>
</template>

<script>
import './counters';

export default {
  name: 'app',
  data () {
    return {
      count: 1
    }
  },
  mounted () {
    this.interval = setInterval(() =>
      this.count += 1, 1000);
  },
  destroyed () {
    clearInterval(this.interval);
  }
}
</script>

// counter/angular/src/app/app.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import './counters';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html'
})
export class AppComponent implements OnInit {
  count = 1;
  interval = undefined;
  ngOnInit() {
    this.interval = setInterval(() =>
      this.count += 1, 1000);
  }
  ngOnDestroy() {
    clearInterval(this.interval);
  }
}

<div>
  <x-count>{{count}}</x-count>
  <x-count-with-shadow>{{count}}</x-count-with-shadow>
</div>
