// libraries/stencil/src/components/component-with-different-views/component-with-different-views.tsx
import { Component, Host, h, Method, Prop } from "@stencil/core";

@Component({
  tag: "component-with-different-views",
  shadow: true
})
export class ComponentWithDifferentViews {
  @Prop() showWC = true;

  @Method()
  async toggle() {
    this.showWC = !this.showWC;
  }

  render() {
    return (
      <Host>
        {this.showWC ? (
          <ce-with-children id="wc"></ce-with-children>
        ) : (
          <div id="dummy">Dummy view</div>
        )}
      </Host>
    );
  }
}

// libraries/svelte/src/components/ComponentWithDifferentViews.svelte
<div id="ce-with-different-views">
    <button on:click={toggle}>Toggle views</button>
    {#if showWC}
        <ce-with-children></ce-with-children>
    {:else}
        <div>Dummy view</div>
    {/if}
</div>

<script>
  let showWC = true;

  export function toggle() {
    showWC = !showWC;
  }
</script>
