// libraries/vue/src/components/ComponentWithProperties.vue
<script setup>
import 'wc/ce-with-properties'

const bool = true;
const num = 42;
const str = 'custom';
const arr = ['c', 'u', 's', 't', 'o', 'm'];
const obj = {org: 'webcomponents', repo: 'custom-elements-everywhere'}
const camelCaseObj = {label: 'passed'}
</script>

<template>
  <ce-with-properties
      id="ce-with-properties"
      :bool.prop="bool"
      :num.prop="num"
      :str.prop="str"
      :arr.prop="arr"
      :obj.prop="obj"
      :camelCaseObj.prop="camelCaseObj"
  ></ce-with-properties>
</template>

// libraries/svelte/src/components/ComponentWithProperties.svelte
<ce-with-properties id="ce-with-properties" {bool} {num} {str} {arr} {obj} {camelCaseObj}></ce-with-properties>

<script>
    let bool = true;
    let num = 42;
    let str = 'custom';
    let arr = ['c', 'u', 's', 't', 'o', 'm'];
    let obj = { org: 'webcomponents', repo: 'custom-elements-everywhere' };
    let camelCaseObj = { label: 'passed' };
</script>
