// libraries/vue/src/components/ComponentWithProperties.vue
<script setup>
import 'wc/ce-with-properties'

const bool = true;
const num = 42;
const str = 'custom';
const arr = ['c', 'u', 's', 't', 'o', 'm'];
const obj = {org: 'webcomponents', repo: 'custom-elements-everywhere'}
const camelCaseObj = {label: 'passed'}
</script>

<template>
  <ce-with-properties
      id="ce-with-properties"
      :bool.prop="bool"
      :num.prop="num"
      :str.prop="str"
      :arr.prop="arr"
      :obj.prop="obj"
      :camelCaseObj.prop="camelCaseObj"
  ></ce-with-properties>
</template>

// libraries/stencil/src/components/component-with-properties.tsx
import { Component, Host, h, Prop } from "@stencil/core";

import 'wc/ce-with-properties';

@Component({
  tag: "component-with-properties",
  shadow: true
})
export class ComponentWithProperties {
  @Prop() bool = true;
  @Prop() num = 42;
  @Prop() str = "custom";
  @Prop() arr = ['c', 'u', 's', 't', 'o', 'm'];
  @Prop() obj = {org: 'webcomponents', repo: 'custom-elements-everywhere'};
  @Prop() camelCaseObj = { label: "passed" };

  render() {
    return (
      <Host>
        <ce-with-properties
          id="ce-with-properties"
          bool={this.bool}
          num={this.num}
          str={this.str}
          arr={this.arr}
          obj={this.obj}
          camelCaseObj={this.camelCaseObj}
        ></ce-with-properties>
      </Host>
    );
  }
}
