// bindings/angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html'
})
export class AppComponent {
  data = {
    boolean: true,
    number: 42,
    string: 'Angular',
    array: ['A', 'n', 'g', 'u', 'l', 'a', 'r'],
    object: { org: 'angular', repo: 'angular' },
    undefinedBoolean: true,
    undefinedNumber: 42,
    undefinedString: 'Angular',
    undefinedArray: ['A', 'n', 'g', 'u', 'l', 'a', 'r'],
    undefinedObject: { org: 'angular', repo: 'angular' },
  }
}

<div>
  <x-element
    [boolean]="data.boolean"
    [number]="data.number"
    [string]="data.string"
    [array]="data.array"
    [object]="data.object"
    [attr.undefined-boolean]="data.undefinedBoolean"
    [attr.undefined-number]="data.undefinedNumber"
    [attr.undefined-string]="data.undefinedString"
    [attr.undefined-array]="data.undefinedArray"
    [attr.undefined-object]="data.undefinedObject"
  ></x-element>
</div>

// bindings/vue/src/App.vue
<template>
  <div id="app">
    <x-element
      :boolean.prop="boolean"
      :number.prop="number"
      :string.prop="string"
      :array.prop="array"
      :object.prop="object"
      :undefined-boolean="undefinedBoolean"
      :undefined-number="undefinedNumber"
      :undefined-string="undefinedString"
      :undefined-array="undefinedArray"
      :undefined-object="undefinedObject"
    ></x-element>
  </div>
</template>

<script>
import './element';

export default {
  name: 'app',
  data () {
    return {
      boolean: true,
      number: 42,
      string: 'Vue',
      array: ['V', 'u', 'e'],
      object: { org: 'vuejs', repo: 'vue' },
      undefinedBoolean: true,
      undefinedNumber: 42,
      undefinedString: 'Vue',
      undefinedArray: ['V', 'u', 'e'],
      undefinedObject: { org: 'vuejs', repo: 'vue' },
    }
  }
}
</script>
