// libraries/solid/src/components.js
/**
 * @license
 * Copyright 2017 Google Inc. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { createSignal } from "solid-js";
import { createStore } from "solid-js/store";
import "ce-without-children";
import "ce-with-children";
import "ce-with-properties";
import "ce-with-inheritance";
import "ce-with-event";

export const ComponentWithoutChildren = () => <ce-without-children />;

export const ComponentWithChildren = () => <ce-with-children />;

export const ComponentWithChildrenRerender = () => {
  const [count, setCount] = createSignal(1);
  Promise.resolve().then(() => setCount(count() + 1));
  return <ce-with-children>{count}</ce-with-children>;
};

export const ComponentWithDifferentViews = ({ setToggle }) => {
  const [show, setShow] = createSignal(true);
  setToggle(() => setShow(!show()));
  return (
    <Show when={show()} fallback={<div id="dummy">Dummy view</div>}>
      <ce-with-children id="wc" />
    </Show>
  );
};

export const ComponentWithProperties = () => {
  const data = {
    bool: true,
    num: 42,
    str: "Solid",
    arr: ["S", "o", "l", "i", "d"],
    obj: { org: "ryansolid", repo: "solid" },
    camelCaseObj: { label: "passed" },
  };
  return (
    <ce-with-properties
      bool={data.bool}
      num={data.num}
      str={data.str}
      arr={data.arr}
      obj={data.obj}
      camelCaseObj={data.camelCaseObj}
    />
  );
};

export const ComponentWithInheritance = () => {
  const data = {
    bool: true,
    num: 42,
    str: "Solid",
    arr: ["S", "o", "l", "i", "d"],
    obj: { org: "ryansolid", repo: "solid" },
    camelCaseObj: { label: "passed" },
  };
  return (
    <ce-with-inheritance
      bool={data.bool}
      num={data.num}
      str={data.str}
      arr={data.arr}
      obj={data.obj}
      camelCaseObj={data.camelCaseObj}
    />
  );
};

export const ComponentWithUnregistered = () => {
  const data = {
    bool: true,
    num: 42,
    str: "Solid",
    arr: ["S", "o", "l", "i", "d"],
    obj: { org: "ryansolid", repo: "solid" },
  };
  return (
    <ce-unregistered
      bool={data.bool}
      num={data.num}
      str={data.str}
      arr={data.arr}
      obj={data.obj}
    />
  );
};

export const ComponentWithImperativeEvent = () => {
  const [eventHandled, setHandled] = createSignal(false),
    handleTestEvent = () => setHandled(true),
    handleCamel = (wc) => wc.addEventListener("camelEvent", handleTestEvent);
  return (
    <>
      <div>{eventHandled().toString()}</div>
      <ce-with-event id="wc" ref={handleCamel} />
    </>
  );
};

export const ComponentWithDeclarativeEvent = () => {
  const [state, setState] = createStore({
      lowercaseHandled: false,
      kebabHandled: false,
      camelHandled: false,
      capsHandled: false,
      pascalHandled: false,
    }),
    handleLowercaseEvent = () => setState("lowercaseHandled", true),
    handleKebabEvent = () => setState("kebabHandled", true),
    handleCamelEvent = () => setState("camelHandled", true),
    handleCapsEvent = () => setState("capsHandled", true),
    handlePascalEvent = () => setState("pascalHandled", true);

  return (
    <>
      <div id="lowercase">{state.lowercaseHandled.toString()}</div>
      <div id="kebab">{state.kebabHandled.toString()}</div>
      <div id="camel">{state.camelHandled.toString()}</div>
      <div id="caps">{state.capsHandled.toString()}</div>
      <div id="pascal">{state.pascalHandled.toString()}</div>
      <ce-with-event
        id="wc"
        on:lowercaseevent={handleLowercaseEvent}
        on:kebab-event={handleKebabEvent}
        on:camelEvent={handleCamelEvent}
        on:CAPSevent={handleCapsEvent}
        on:PascalEvent={handlePascalEvent}
      />
    </>
  );
};

// libraries/react-experimental/src/components.js
/**
 * @license
 * Copyright 2017 Google Inc. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import React, { Component } from 'react';
import 'ce-without-children';
import 'ce-with-children';
import 'ce-with-properties';
import 'ce-with-inheritance';
import 'ce-with-event';

export class ComponentWithoutChildren extends Component {
  render() {
    return (
      <div>
        <ce-without-children ref={(el) => this.wc = el}></ce-without-children>
      </div>
    );
  }
}

export class ComponentWithChildren extends Component {
  render() {
    return (
      <div>
        <ce-with-children ref={(el) => this.wc = el}></ce-with-children>
      </div>
    );
  }
}

export class ComponentWithChildrenRerender extends Component {
  constructor () {
    super();
    this.state = { count: 1 };
  }
  componentDidMount () {
    Promise.resolve().then(_ => this.setState({count: this.state.count += 1}));
  }
  componentWillUnmount () {
    clearInterval(this.interval);
  }
  render () {
    const { count } = this.state;
    return (
      <div>
        <ce-with-children ref={(el) => this.wc = el}>{count}</ce-with-children>
      </div>
    );
  }
}

export class ComponentWithDifferentViews extends Component {
  constructor () {
    super();
    this.state = { showWC: true };
  }
  toggle() {
    this.setState({ showWC: !this.state.showWC });
  }
  render () {
    const { showWC } = this.state;
    return (
      <div>
        {showWC ? (
          <ce-with-children ref={(el) => this.wc = el}></ce-with-children>
        ) : (
          <div ref="dummy">Dummy view</div>
        )}
      </div>
    );
  }
}

export class ComponentWithProperties extends Component {
  render () {
    const data = {
      bool: true,
      num: 42,
      str: 'React',
      arr: ['R', 'e', 'a', 'c', 't'],
      obj: { org: 'facebook', repo: 'react' },
      camelCaseObj: { label: "passed" }
    };
    return (
      <div>
        <ce-with-properties ref={(el) => this.wc = el}
          bool={data.bool}
          num={data.num}
          str={data.str}
          arr={data.arr}
          obj={data.obj}
          camelCaseObj={data.camelCaseObj}
        ></ce-with-properties>
      </div>
    );
  }
}

export class ComponentWithInheritance extends Component {
  render () {
    const data = {
      bool: true,
      num: 42,
      str: 'React',
      arr: ['R', 'e', 'a', 'c', 't'],
      obj: { org: 'facebook', repo: 'react' },
      camelCaseObj: { label: "passed" }
    };
    return (
      <div>
        <ce-with-inheritance ref={(el) => this.wc = el}
          bool={data.bool}
          num={data.num}
          str={data.str}
          arr={data.arr}
          obj={data.obj}
          camelCaseObj={data.camelCaseObj}
        ></ce-with-inheritance>
      </div>
    );
  }
}

export class ComponentWithUnregistered extends Component {
  render () {
    const data = {
      bool: true,
      num: 42,
      str: 'React',
      arr: ['R', 'e', 'a', 'c', 't'],
      obj: { org: 'facebook', repo: 'react' }
    };
    return (
      <div>
        {/* This element doesn't actually exist.
        It's used to test unupgraded behavior. */}
        <ce-unregistered ref={(el) => this.wc = el}
          bool={data.bool}
          num={data.num}
          str={data.str}
          arr={data.arr}
          obj={data.obj}
        ></ce-unregistered>
      </div>
    );
  }
}

export class ComponentWithImperativeEvent extends Component {
  constructor() {
    super();
    this.state = {
      eventHandled: false
    };
    this.handleTestEvent = this.handleTestEvent.bind(this);
  }
  componentDidMount() {
    this.wc.addEventListener('camelEvent', this.handleTestEvent);
  }
  handleTestEvent(e) {
    this.setState({ eventHandled: true });
  }
  render() {
    let state = this.state;
    return (
      <div>
        <div ref={(el) => this.handled = el}>{state.eventHandled.toString()}</div>
        <ce-with-event id="wc" ref={(el) => this.wc = el}></ce-with-event> 
      </div>
    );
  }
}

export class ComponentWithDeclarativeEvent extends Component {
  constructor() {
    super();
    this.state = {
      lowercaseHandled: false,
      kebabHandled: false,
      camelHandled: false,
      capsHandled: false,
      pascalHandled: false
    };
    this.handleLowercaseEvent = this.handleLowercaseEvent.bind(this);
    this.handleKebabEvent = this.handleKebabEvent.bind(this);
    this.handleCamelEvent = this.handleCamelEvent.bind(this);
    this.handleCapsEvent = this.handleCapsEvent.bind(this);
    this.handlePascalEvent = this.handlePascalEvent.bind(this);
  }
  handleLowercaseEvent(e) {
    this.setState({ lowercaseHandled: true });
  }
  handleKebabEvent(e) {
    this.setState({ kebabHandled: true });
  }
  handleCamelEvent(e) {
    this.setState({ camelHandled: true });
  }
  handleCapsEvent(e) {
    this.setState({ capsHandled: true });
  }
  handlePascalEvent(e) {
    this.setState({ pascalHandled: true });
  }
  render() {
    let state = this.state;
    return (
      <div>
        <div ref={(el) => this.lowercase = el}>{state.lowercaseHandled.toString()}</div>
        <div ref={(el) => this.kebab = el}>{state.kebabHandled.toString()}</div>
        <div ref={(el) => this.camel = el}>{state.camelHandled.toString()}</div>
        <div ref={(el) => this.caps = el}>{state.capsHandled.toString()}</div>
        <div ref={(el) => this.pascal = el}>{state.pascalHandled.toString()}</div>
        <ce-with-event id="wc" ref={(el) => this.wc = el}
          onlowercaseevent={this.handleLowercaseEvent}
          onkebab-event={this.handleKebabEvent}
          oncamelEvent={this.handleCamelEvent}
          onCAPSevent={this.handleCapsEvent}
          onPascalEvent={this.handlePascalEvent}
        ></ce-with-event> 
      </div>
    );
  }
}
